apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: marwan1408/server1:latest
          ports:
            - containerPort: 5050
          env:
            - name: ATLAS_URL
              valueFrom:
                secretKeyRef:
                  name: atlas-secret
                  key: ATLAS_URL
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: NodePort
  ports:
    - port: 5050
  selector:
    app: server
